routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Illuminate\Support\Facades\Route;
use Sentrio\Http\Controllers\DashboardController;
use Sentrio\User\Controllers\ForgotPasswordController;
use Sentrio\User\Controllers\LoginController;
use Sentrio\User\Controllers\ResetPasswordController;

Route::group([
    'middleware' => ['web'],
    'prefix' => config('sentrio.prefix'),
    'namespace' => 'Sentrio',
    'as' => 'admin.'
], function () {
    // login / logout
    Route::get('/login', [LoginController::class, 'showLoginForm'])->name('login');
    Route::post('login', [LoginController::class, 'login'])->name('login.post');
    Route::post('logout', [LoginController::class, 'logout'])->name('logout');

    // forgot password
    Route::get('password/reset', [ForgotPasswordController::class, 'showLinkRequestForm'])->name('password.request');
    Route::post('password/email', [ForgotPasswordController::class, 'sendResetLinkEmail'])->name('password.email');

    // reset password
    Route::get('password/reset/{token}', [ResetPasswordController::class, 'showResetForm'])->name('password.reset');
    Route::post('password/reset', [ResetPasswordController::class, 'reset'])->name('password.update');
});

Route::group([
    'middleware' => ['web', 'admin.auth:admin', 'permission'],
    'prefix' => config('sentrio.prefix'),
    'as' => 'admin.',
    'namespace' => 'Sentrio'
], function () {
    // dashboard
    Route::get('', [DashboardController::class, 'index'])->name('dashboard');

    // resources
    Route::resource('admin-user', User\Controllers\AdminUserController::class);
    // attribute
    // category
    // currency
    // language
    // order
    // order status
    // menu group
    // property
    // product
    // role
    // state
    Route::resource('user-group', User\Controllers\UserGroupController::class);
    // tax group
    // tax rate
});

resources/views/admin-user/_fields.blade.php
<div class="mt-3 flex w-full">
    <base-input
        label-text="{{ __('sentrio::core.admin-user.first_name') }}"
        field-name="first_name"
        init-value="{{ $adminUser->first_name ?? '' }}"
        error-text="{{ $errors->first('first_name') }}"
    ></base-input>
</div>

<div class="mt-3 flex w-full">
    <base-input
        label-text="{{ __('sentrio::core.admin-user.last_name') }}"
        field-name="last_name"
        init-value="{{ $adminUser->last_name ?? '' }}"
        error-text="{{ $errors->first('last_name') }}"
    ></base-input>
</div>

<div class="mt-3 flex w-full">
    <base-input
        label-text="{{ __('sentrio::core.admin-user.is_super_admin') }}"
        field-name="is_super_admin"
        init-value="{{ $adminUser->is_super_admin ?? '' }}"
        error-text="{{ $errors->first('is_super_admin') }}"
    ></base-input>
</div>

<div class="mt-3 flex w-full">
    <base-input
        label-text="{{ __('sentrio::core.admin-user.email') }}"
        field-name="email"
        init-value="{{ $adminUser->email ?? '' }}"
        error-text="{{ $errors->first('email') }}"
        :is-disabled="true"
    ></base-input>
</div>

<div class="mt-3 flex w-full">
    <base-input
        label-text="{{ __('sentrio::core.admin-user.image_file') }}"
        field-name="image_path"
        init-value="{{ $adminUser->image_path ?? '' }}"
        error-text="{{ $errors->first('image_path') }}"
        upload-url="{{ route('admin.admin-user-image-upload') }}"
    ></base-input>
</div>

@if (!isset($adminUser))
    <div class="mt-3 flex w-full">
        <base-input
            label-text="{{ __('sentrio::core.admin-user.password') }}"
            field-name="password"
            init-value="{{ $adminUser->password ?? '' }}"
            error-text="{{ $errors->first('password') }}"
            type="password"
        ></base-input>
    </div>

    <div class="mt-3 flex w-full">
        <base-input
            label-text="{{ __('sentrio::core.admin-user.password_confirmation') }}"
            field-name="password_confirmation"
            init-value="{{ $adminUser->password_confirmation ?? '' }}"
            error-text="{{ $errors->first('password_confirmation') }}"
            type="password_confirmation"
        ></base-input>
    </div>
@endif

<div class="mt-3 flex w-full">
    <base-select
        label-text="{{ __('sentrio::core.admin-user.language') }}"
        field-name="language"
        init-value="{{ $adminUser->language ?? '' }}"
        error-text="{{ $errors->first('language') }}"
        :options="{{ json_encode($languageOptions) }}"
    ></base-select>
</div>

<div class="mt-3 flex w-full">
    <base-select
        label-text="{{ __('sentrio::core.admin-user.role_id') }}"
        field-name="role_id"
        init-value="{{ $adminUser->role_id ?? '' }}"
        error-text="{{ $errors->first('role_id') }}"
        :options="{{ json_encode($roleOptions) }}"
    ></base-select>
</div>

resources/views/admin-user/create.blade.php
@extends('sentrio::layouts.app')

@section('meta_title')
    {{ __('sentrio::core.admin-user.create') }}
@endsection

@section('page_title')
    <div class="text-gray-800 flex items-center">
        <div class="text-xl text-red-700 font-semibold">
            {{ __('sentrio::core.admin-user.create') }}
        </div>
    </div>
@endsection

@section('content')
    <div class="flex items-center">
        <admin-user-save base-url="{{ asset(config('sentrio.prefix')) }}" inline-template>
            <div class="w-full block">
                <form method="post" action="{{ route('admin.admin-user.store') }}">
                    @csrf

                    <base-tabs>
                        @foreach ($tabs as $tab)
                            <base-tab identifier="{{ $tab->key() }}" name="{{ $tab->label() }}">
                                @php
                                    $path = $tab->view();
                                @endphp

                                @include($path)
                            </base-tab>
                        @endforeach
                    </base-tabs>

                    <div class="mt-3 py-3">
                        <button type="submit" class="px-6 py-3 font-semibold leading-7 text-white hover:text-white bg-red-600 rounded hover:bg-red-700">
                            <svg xmlns="http://www.w3.org/2000/svg" class="h-4 inline-flex w-4" fill="currentColor" viewBox="0 0 20 20">
                                <path d="M0 2C0 .9.9 0 2 0h14l4 4v14a2 2 0 0 1-2 2H2a2 2 0 0 1-2-2V2zm5 0v6h10V2H5zm6 1h3v4h-3V3z"/>
                            </svg>
                            <span class="ml-3">
                                {{ __('sentrio::core.btn.save') }}
                            </span>
                        </button>

                        <a href="{{ route('admin.admin-user.index') }}" class="px-6 py-3 font-semibold inline-block text-white leading-7 hover:text-white bg-gray-500 rounded hover:bg-gray-600">
                            <span class="leading-7">
                                {{ __('sentrio::core.btn.cancel') }}
                            </span>
                        </a>
                    </div>
                </form>
            </div>
        </admin-user-save>
    </div>
@endsection

resources/views/admin-user/edit.blade.php
@extends('sentrio::layouts.app')

@section('meta_title')
    {{ __('sentrio::core.admin-user.edit') }}
@endsection

@section('page_title')
    <div class="text-gray-800 flex items-center">
        <div class="text-xl text-red-700 font-semibold">
            {{ __('sentrio::core.admin-user.edit') }}
        </div>
    </div>
@endsection

@section('content')
    <div class="flex items-center">
        <admin-user-save base-url="{{ asset(config('sentrio.prefix')) }}" :admin-user="{{ $adminUser }}" inline-template>
            <div class="w-full block">
                <form method="post" action="{{ route('admin.admin-user.update', $adminUser->id) }}">
                    @csrf
                    @method('put')

                    <base-tabs>
                        @foreach ($tabs as $tab)
                            <base-tab identifier="{{ $tab->key() }}" name="{{ $tab->label() }}">
                                @php
                                    $path = $tab->view();
                                @endphp

                                @include($path)
                            </base-tab>
                        @endforeach
                    </base-tabs>

                    <div class="mt-3 py-3">
                        <button type="submit" class="px-6 py-3 font-semibold leading-7 text-white hover:text-white bg-red-600 rounded hover:bg-red-700">
                            <svg xmlns="http://www.w3.org/2000/svg" class="h-4 inline-flex w-4" fill="currentColor" viewBox="0 0 20 20">
                                <path d="M0 2C0 .9.9 0 2 0h14l4 4v14a2 2 0 0 1-2 2H2a2 2 0 0 1-2-2V2zm5 0v6h10V2H5zm6 1h3v4h-3V3z"/>
                            </svg>
                            <span class="ml-3">
                                {{ __('sentrio::core.btn.save') }}
                            </span>
                        </button>

                        <a href="{{ route('admin.admin-user.index') }}" class="px-6 py-3 font-semibold inline-block text-white leading-7 hover:text-white bg-gray-500 rounded hover:bg-gray-600">
                            <span class="leading-7">
                                {{ __('sentrio::core.btn.cancel') }}
                            </span>
                        </a>
                    </div>
                </form>
            </div>
        </admin-user-save>
    </div>
@endsection

resources/views/admin-user/index.blade.php
@extends('sentrio::layouts.app')

@section('meta_title')
    {{ __('sentrio::core.admin-user.index') }}
@endsection

@section('page_title')
    <div class="text-gray-800 flex items-center">
        <div class="text-xl text-ted-700 font-semibold">
            {{ __('sentrio::core.admin-user.index') }}
        </div>

        <div class="ml-auto">
            <a href="{{ route('admin.admin-user.create') }}" class="px-4 py-2 font-semibold leading-7 text-white hover:text-white bg-red-600 rounded hover:bg-red-700">
                <svg class="w-5 h-5 inline-block text-white" fill="currentColor" viewBox="0 0 24 24">
                    <path d="M17 11a1 1 0 0 1 0 2h-4v4a1 1 0 0 1-2 0v-4H7a1 1 0 0 1 0-2h4V7a1 1 0 0 1 2 0v4h4z"/>
                </svg>
                {{ __('sentrio::core.btn.create') }}
            </a>
        </div>
    </div>
@endsection

@section('content')
    <admin-user-table :init-admin-users="{{ json_encode($adminUsers) }}" base-url="{{ asset(config('sentrio.prefix')) }}"></admin-user-table>
@endsection

resources/views/admin.blade.php
@extends('sentrio::layouts.app')

@section('meta_title')
    Sentrio eCommerce Admin Dashboard
@endsection

@section('page_title')
    <div class="text-gray-800 flex items-center">
        <div class="text-xl text-red-700 font-semibold">
            {{ __('Dashboard') }}
        </div>
    </div>
@endsection

@section('content')
    <div class="flex justify-around my-5">
        {{ $customerWidget->render() }}
        {{ $orderWidget->render() }}
        {{ $revenueWidget->render() }}
    </div>

    <div class="flex mt-5 justify-around my-5">
        <div class="bg-white border border-gray-400 w-full rounded">
            <div class="font-semibold text-md p-4 border-b">
                Admin Dashboard
            </div>
        </div>
    </div>
@endsection

resources/views/breadcrumb/index.blade.php
<div class="mt-1 ml flex items-center">
    @if (isset($breadcrumb->parents) && $breadcrumb->parents->count() > 0)
        @foreach ($breadcrumb->parents as $parentBreadcrumb)
            <div class="ml-1">
                <a href="{{ route($parentBreadcrumb->route) }}">
                    {{ __($parentBreadcrumb->label) }}
                </a>
            </div>
        @endforeach
    @endif

    <div class="ml-1">
        {{ __($breadcrumb->label) }}
    </div>
</div>

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <!-- CSRF Token -->
        <meta name="csrf-token" content="{{ csrf_token() }}">

        <title>@yield('meta_title', 'Sentrio eCommerce')</title>

        <!-- Fonts -->
        <link rel="dns-prefetch" href="//fonts.gstatic.com">
        <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

        <!-- Styles -->
        @if (file_exists(public_path('mix-manifest.json')))
            <link href="{{ mix('css/app.css') }}" rel="stylesheet">
        @else
            <link href="{{ asset('css/app.css') }}" rel="stylesheet">
        @endif
    </head>
    <body>
        <div id="app">

            <base-alert></base-alert>
            <base-dialog></base-dialog>
            <app-layout inline-template>

                <div class="flex items-start">
                    <div :class="sidebar ? 'w-16 z-0 transition sidebar-collapsed duration-500' : 'w-64'">
                        @include('sentrio::partials.sidebar')
                    </div>

                    <div class="w-full">
                        <div class="w-full">
                            @include('sentrio::partials.header')
                            @include('sentrio::partials.flash')
                            @include('sentrio::partials.breadcrumb')

                            <h1 class="mx-4 my-3">
                                @yield('page_title')
                            </h1>

                            <div class="rounded p-5 mx-3 my-3 bg-white">
                                @yield('content')
                            </div>

                            @include('sentrio::partials.footer')
                        </div>
                    </div>
                </div>
            </app-layout>
        </div>

        <!-- Scripts -->
        @if (file_exists(public_path('mix-manifest.json')))
            <script src="{{ mix('js/sentrio.js') }}"></script>
        @else
            <script src="{{ asset('js/sentrio.js') }}"></script>
        @endif

        @stack('scripts')

        @if (file_exists(public_path('mix-manifest.json')))
            <script src="{{ mix('js/app.js') }}"></script>
        @else
            <script src="{{ asset('js/app.js') }}"></script>
        @endif
    </body>
</html>

resources/views/partials/breadcrumb.blade.php
<div class="ml-4 my-3">
    {!! Breadcrumb::render(request()->route()->getName()) !!}
</div>

resources/views/partials/flash.blade.php
<app-flash success-notification="{{ session()->get('successNotification') }}" inline-template>
    <div></div>
</app-flash>

resources/views/partials/footer.blade.php
<footer class="text-gray-700 body-font">
    <div class="container px-5 py-8 mx-auto flex items-center sm:flex-row flex-col">
        <a class="flex title-font font-medium items-center md:justify-start justify-center text-gray-900">
            <img src="{{ asset('img/logo.png') }}" class="h-10 w-10" />
        </a>
    </div>
</footer>

resources/views/partials/header.blade.php
<div class="bg-white z-1 shadow p-0">
    <div class="flex px-3 py-2 h-16 items-center">
        <div class="mr-auto ml-3 cursor-pointer">
            <svg xmlns="http://www.w3.org/2000/svg" class="w-5 h-5" @click="sidebar = !sidebar">
                <path d="M1 1h18v2H1V1zm6 8h12v2H7V9zm-6 8h18v2H1v-2zM7 5h12v2H7V5zm0 8h12v2H7v-2zM1 6l4 4-4 4V6z"/>
            </svg>
        </div>

        <div class="ml-auto flex items-center mr-3">
            <div class="relative inset-0" @click="isVisible = false">
                <div class="relative inline-block" @mouseover="isVisible = true" @mouseleave="isVisible = false" @keydown.enter="isVisible = !isVisible">
                    <button type="button" class="inline-flex items-center justify-between px-2 py-1 font-medium text-gray-700 transition-all duration-500 rounded-md focus:outline-none focus:text-brand-900 sm:focus:shadow-outline">
                        <span class="flex-shrink-0">
                            {{ Auth::guard('admin')->user()->full_name }}
                        </span>

                        <svg fill="currentColor" viewBox="0 0 20 20" class="flex-shrink-0 w-5 h-5 ml-1">
                            <path :class="{ 'rotate-180': isVisible }" class="transition duration-300 ease-in-out origin-center transform" fill-rule="evenodd" d="M5.293 7.293a1 1 0 011.414 0L10 10.586l3.293-3.293a1 1 0 111.414 1.414l-4 4a1 1 0 01-1.414 0l-4-4a1 1 0 010-1.414z" clip-rule="evenodd"></path>
                        </svg>
                    </button>

                    <transition enter-active-class="transition duration-300 ease-out transform" enter-class="-translate-y-3 scale-95 opacity-0" enter-to-class="translate-y-0 scale-100 opacity-100" leave-active-class="transition duration-150 ease-in transform" leave-class="translate-y-0 opacity-100" leave-to-class="-translate-y-3 opacity-0">
                        <div v-show="isVisible" class="absolute w-full pt-2">
                            <div class="relative mt-2 py-3 bg-white border border-gray-200">
                                <a href="{{ route('admin.logout') }}" onclick="event.preventDefault();document.getElementById('admin-logout-form').submit();" class="w-full py-4 px-4 font-medium text-gray-700 hover:bg-gray-100 focus:outline-none hover:text-gray-900 focus:text-gray-900 focus:shadow-outline transition duration-300 ease-in-out">
                                    {{ __('Logout') }}
                                </a>

                                <form action="{{ route('admin.logout') }}" id="admin-logout-form" method="POST" style="display: none;">
                                    @csrf
                                </form>
                            </div>
                        </div>
                    </transition>
                </div>
            </div>
        </div>
    </div>
</div>

resources/views/partials/sidebar.blade.php
<div class="bg-white border-r min-h-screen">
    <div class="flex items-center">
        <a href="{{ route('admin.dashboard') }}" class="flex items-center mt-2">
            <img class="h-12 block ml-6 w-12" src="{{ asset('vendor/sentrio/img/logo.png') }}" />

            <div class="text-xl text-red-600" :class="sidebar ? 'hidden' : ''">
                Sentrio
            </div>
        </a>
    </div>

    <nav class="mt-10">
        {{-- @foreach ($adminMenus as $key => $adminMenu)
            <base-menu :sidebar="sidebar" :menu="{{ json_encode($adminMenu) }}"></base-menu>
        @endforeach --}}
    </nav>
</div>

resources/views/user-group/index.blade.php
@extends('sentrio::layouts.app')

@section('meta_title')
    {{ __('User Group') }}
@endsection

@section('page_title')
    <div class="text-gray-800 flex items-center">
        <div class="text-xl text-red-700 font-semibold">
            {{ __('User Group') }}
        </div>

        <div class="ml-auto">
            <a href="{{ route('admin.user-group.create') }}" class="px-4 py-2 font-semibold leading-7 text-white hover:text-white bg-red-600 rounded hover:bg-red-700">
                <svg class="w-5 h-5 inline-block text-white" fill="currentColor" viewBox="0 0 24 24">
                    <path d="M17 11a1 1 0 0 1 0 2h-4v4a1 1 0 0 1-2 0v-4H7a1 1 0 0 1 0-2h4V7a1 1 0 0 1 2 0v4h4z"/>
                </svg>

                {{ __('Create') }}
            </a>
        </div>
    </div>
@endsection

@section('content')
    <div>
        {{ USER GROUP TABLE HERE }}
    </div>
@endsection

resources/views/widget/total-customer.blade.php
<div class="w-64 cursor-pointer bg-red-600 ml-3 border text-center b-gray-400 rounded items-center p-6 text-white">
    <div class="text-md border-b pb-3 font-bold w-full">
        <span class="uppercase">
            {{ __('Total Customer') }}
        </span>
    </div>

    <div class="flex mt-5 text-center justify-around items-center">
        <div class="w-12 h-12">
            <svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 20">
                <path d="M7 8a4 4 0 1 1 0-8 4 4 0 0 1 0 8zm0 1c2.15 0 4.2.4 6.1 1.09L12 16h-1.25L10 20H4l-.75-4H2L.9 10.09A17.93 17.93 0 0 1 7 9zm8.31.17c1.32.18 2.59.48 3.8.92L18 16h-1.25L16 20h-3.96l.37-2h1.25l1.65-8.83zM13 0a4 4 0 1 1-1.33 7.76 5.96 5.96 0 0 0 0-7.52C12.1.1 12.53 0 13 0z"/>
            </svg>
        </div>

        <div class="text-4xl ml-5 font-bold">
            {{ $value }}
        </div>
    </div>
</div>

resources/views/widget/total-order.blade.php
<div class="w-64 cursor-pointer bg-purple-500 ml-3 border text-center b-gray-400 rounded items-center p-6 text-white">
    <div class="text-md border-b pb-3 font-bold w-full">
        <span class="uppercase">
            {{ __('Total Order') }}
        </span>
    </div>

    <div class="flex mt-5 text-center justify-around items-center">
        <div class="w-12 h-12">
            <svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 20">
                <path d="M18 6V4H2v2h16zm0 4H2v6h16v-6zM0 4c0-1.1.9-2 2-2h16a2 2 0 0 1 2 2v12a2 2 0 0 1-2 2H2a2 2 0 0 1-2-2V4zm4 8h4v2H4v-2z"/>
            </svg>
        </div>

        <div class="text-4xl ml-5 font-bold">
            {{ $value }}
        </div>
    </div>
</div>

resources/views/widget/total-revenue.blade.php
<div class="w-64 cursor-pointer bg-blue-600 ml-3 border text-center b-gray-400 rounded items-center p-6 text-white">
    <div class="text-md border-b pb-3 font-bold w-full">
        <span class="uppercase">
            {{ __('Total Revenue') }}
        </span>
    </div>

    <div class="flex mt-5 text-center justify-around items-center">
        <div class="w-12 h-12">
            <svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 20">
                <path d="M4.13 12H4a2 2 0 1 0 1.8 1.11L7.86 10a2.03 2.03 0 0 0 .65-.07l1.55 1.55a2 2 0 1 0 3.72-.37L15.87 8H16a2 2 0 1 0-1.8-1.11L12.14 10a2.03 2.03 0 0 0-.65.07L9.93 8.52a2 2 0 1 0-3.72.37L4.13 12zM0 4c0-1.1.9-2 2-2h16a2 2 0 0 1 2 2v12a2 2 0 0 1-2 2H2a2 2 0 0 1-2-2V4z"/>
            </svg>
        </div>

        <div class="text-4xl ml-5 font-bold">
            {{ $value }}
        </div>
    </div>
</div>